name: CI

on: 
  push:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup Node.js and npm
        uses: actions/setup-node@v4
      
      - name: Install dependencies
        run: npm ci

      - name: Run typecheck
        run: npm run typecheck

      - name: Run Vitest
        run: npm test

  lint:
    name: run linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js and npm
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      


        
